##
# Copyright © 2020, The Gust Framework Authors. All rights reserved.
#
# The Gust/Elide framework and tools, and all associated source or object computer code, except where otherwise noted,
# are licensed under the Zero Prosperity license, which is enclosed in this repository, in the file LICENSE.txt. Use of
# this code in object or source form requires and implies consent and agreement to that license in principle and
# practice. Source or object code not listing this header, or unless specified otherwise, remain the property of
# Elide LLC and its suppliers, if any. The intellectual and technical concepts contained herein are proprietary to
# Elide LLC and its suppliers and may be covered by U.S. and Foreign Patents, or patents in process, and are protected
# by trade secret and copyright law. Dissemination of this information, or reproduction of this material, in any form,
# is strictly forbidden except in adherence with assigned license requirements.
##

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: todolist
  labels:
    app: todolist
    role: cache
    environment: production
spec:
  ports:
    - port: 6379
      protocol: TCP
      name: tls-redis
  selector:
    app: todolist
    role: cache
    environment: production
  type: NodePort
  publishNotReadyAddresses: yes
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: todolist
  labels:
    app: todolist
    role: server
    environment: production
spec:
  ports:
    - name: tls-app
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tls-rpc
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: todolist
    role: server
    environment: production
  type: NodePort
  publishNotReadyAddresses: yes
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-usw2
  namespace: todolist
  labels:
    app: todolist
    role: server
    environment: production
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  ports:
    - name: tls-app
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tls-rpc
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: todolist
    role: server
    environment: production
  type: LoadBalancer
  publishNotReadyAddresses: yes
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: todolist
  labels:
    app: todolist
    role: gateway
    environment: production
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"443": {}, "80": {}}}'
    cloud.google.com/app-protocols: '{"tls-gateway": "HTTP2"}'
    cloud.google.com/backend-config: '{"ports": {"443":"todolist-server", "80": "todolist-redirect"}}'
spec:
  ports:
    - name: http-gateway
      port: 80
      protocol: TCP
      targetPort: 80
    - name: tls-gateway
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: todolist
    role: gateway
    environment: production
  type: NodePort
  publishNotReadyAddresses: yes
