apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: todolist
  labels:
    app: todolist
    role: cache
    environment: production
spec:
  ports:
    - port: 6379
      protocol: TCP
      name: tls-redis
  selector:
    app: todolist
    role: cache
    environment: production
  type: NodePort
  publishNotReadyAddresses: yes
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: todolist
  labels:
    app: todolist
    role: server
    environment: production
spec:
  ports:
    - name: tls-app
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tls-rpc
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: todolist
    role: server
    environment: production
  type: NodePort
  publishNotReadyAddresses: yes
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-usw2
  namespace: todolist
  labels:
    app: todolist
    role: server
    environment: production
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  ports:
    - name: tls-app
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tls-rpc
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: todolist
    role: server
    environment: production
  type: LoadBalancer
  publishNotReadyAddresses: yes
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: todolist
  labels:
    app: todolist
    role: gateway
    environment: production
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"443": {}}}'
    cloud.google.com/app-protocols: '{"tls-gateway": "HTTP2"}'
    cloud.google.com/backend-config: '{"ports": {"443":"todolist-server"}}'
spec:
  ports:
    - name: tls-gateway
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: todolist
    role: gateway
    environment: production
  type: NodePort
  publishNotReadyAddresses: yes
