apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: todolist-server
  namespace: todolist
  labels:
    environment: production
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 120
  sessionAffinity:
    affinityType: COOKIE
    affinityCookieTtlSec: 300
  cdn:
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
