apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grpc-py
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v2
      kind: Module
      name: ambassador
      config:
        enable_grpc_web: True
spec:
  grpc: True
  prefix: /todolist.Tasks/
  rewrite: /todolist.Tasks/
  service: tasks
