
steps:

# Build: Gust Framework
- name: 'l.gcr.io/google/bazel:2.1.0'
  id: build
  args:
  - --bazelrc=.bazelrc
  - build
  - --config=ci
  - --
  - //gust/...

# Image build: Todolist App
- name: 'l.gcr.io/google/bazel:2.1.0'
  id: todolist
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --define=todolist_release_tag=$SHORT_SHA
    - --
    - //samples/todolist/src:TodolistServer-image-push

# Image pull: Built App
- name: 'gcr.io/cloud-builders/docker'
  id: pull
  args: ['pull', "us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA"]

# Image tag: Latest
- name: 'gcr.io/cloud-builders/docker'
  id: tag
  args: ['tag', 'us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

# Image push: Latest
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

# Credentials: K8S
- name: 'gcr.io/cloud-builders/gcloud'
  id: cluster
  args: [
    'container',
    'clusters',
    'get-credentials',
    'k9-v4c',
    '--zone',
    'us-west2-c',
    '--project',
    'bloom-sandbox'
  ]

# Deploy: K8S (Envoy)
- name: 'l.gcr.io/google/bazel:2.1.0'
  id: deploy-envoy
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --
    - //samples/todolist/src/config:envoy.replace

# Deploy: K8S (Todolist)
- name: 'l.gcr.io/google/bazel:2.1.0'
  id: deploy-todolist
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --
    - //samples/todolist/src/config:todolist.replace

images:
  - us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA
  - us.gcr.io/elide-tools/sample/todolist/jvm:latest

tags: ['framework', 'tools', 'gust']

timeout: 10m
options:
  machineType: "N1_HIGHCPU_8"
  sourceProvenanceHash: ['SHA256']
