
steps:

# Remote build: Gust Framework
- name: 'l.gcr.io/google/bazel'
  args:
  - --bazelrc=.bazelrc
  - build
  - --config=ci
  - --
  - //gust/...

# Image build: Todolist App
- name: 'l.gcr.io/google/bazel'
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --define=todolist_release_tag=$SHORT_SHA
    - --
    - //samples/todolist/src:TodolistServer-image-push

timeout: 30m
options:
  machineType: "N1_HIGHCPU_8"

images:
  - us.gcr.io/elide-tools/sample/todolist/jvm
