
steps:

# Build: Gust Framework
- name: 'l.gcr.io/google/bazel'
  id: build
  args:
  - --bazelrc=.bazelrc
  - build
  - --config=ci
  - --
  - //gust/...

# Image build: Todolist App
- name: 'l.gcr.io/google/bazel'
  id: todolist
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --define=todolist_release_tag=$SHORT_SHA
    - --
    - //samples/todolist/src:TodolistServer-image-push

# Image pull: Built App
- name: 'gcr.io/cloud-builders/docker'
  id: pull
  args: ['pull', "us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA"]

# Image tag: Latest
- name: 'gcr.io/cloud-builders/docker'
  id: tag
  args: ['tag', 'us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

# Image push: Latest
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

images:
  - us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA
  - us.gcr.io/elide-tools/sample/todolist/jvm:latest

tags: ['framework', 'tools', 'gust']

timeout: 10m
options:
  machineType: "N1_HIGHCPU_8"
  sourceProvenanceHash: ['SHA256']
