
steps:

# Build: Gust Framework
- name: 'l.gcr.io/google/bazel'
  args:
  - --bazelrc=.bazelrc
  - build
  - --config=ci
  - --
  - //samples/todolist/src:TodolistServer_deploy.jar
  - //gust/...

# Image build: Todolist App
- name: 'l.gcr.io/google/bazel'
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --define=todolist_release_tag=$SHORT_SHA
    - --
    - //samples/todolist/src:TodolistServer-image-push

# Image pull: Built App
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', "us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA"]

# Image tag: Latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

# Image push: Latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

images:
  - us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA
  - us.gcr.io/elide-tools/sample/todolist/jvm:latest

artifacts:
  objects:
    location: 'gs://elide-artifacts/'
    paths: ['dist/bin/samples/todolist/src/TodolistServer_deploy.jar']

tags: ['framework', 'tools', 'gust']

timeout: 10m
options:
  machineType: "N1_HIGHCPU_8"
  sourceProvenanceHash: ['SHA256']
