steps:
  - command: "make build CI=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":package: Build: Framework"

  - command: "make build CI=yes BAZELISK=/sdk/bazel/bin/bazelisk TARGETS='//javatests/ssr:SSRTestApplication-native-bin && make build CI=yes BAZELISK=/sdk/bazel/bin/bazelisk TARGETS='//javatests/basic:BasicTestApplication-native-bin"
    label: ":clamp: Build: Native Images"

  - wait

  - command: "make build test CI=yes TARGETS='//javatests/...' BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":hammer: Testsuite"

  - wait

  - command: "make build samples CI=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":whale: Release: Images"
    #branches: "master"
