steps:
  - command: "make build CI=yes CACHE=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":package: Build"

  - wait

  - command: "make test CI=yes CACHE=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":hammer: Testsuite"

  - command: "make samples CI=yes CACHE=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":whale: Bake Images"
    branches: "master"
