steps:
  - command: "make build test CI=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":package: Build: Framework"

  - command: "make test CI=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":hammer: Testsuite"

  - wait

  - command: "make build samples CI=yes BAZELISK=/sdk/bazel/bin/bazelisk"
    label: ":whale: Release: Images"
    #branches: "master"
