steps:
  - command: "gcloud auth configure-docker && make build CI=yes CACHE=yes"
    label: ":package: Build"

  - wait

  - command: "make test CI=yes CACHE=yes"
    label: ":hammer: Testsuite"

  - command: "make samples CI=yes CACHE=yes"
    label: ":whale: Bake Images"
    branches: "master"
