steps:
  - command: "make build CI=yes"
    label: ":bazel: Build: Framework"

  - command: "make build CI=yes && make test CI=yes TESTS='//javatests/... -javatests/server:BrowserBasicServerTest_chromium-local -javatests/server:BrowserBasicServerTest_firefox-local -javatests/server:BasicTestApplication-native -javatests/ssr:SSRTestApplication-native-bin'"
    label: ":coverage: Testsuite"

  - wait

  - command: "make build CI=yes TARGETS='//javatests/ssr:SSRTestApplication-native-bin && make build CI=yes TARGETS='//javatests/server:BasicTestApplication-native-bin"
    label: ":java: Build: Native Binaries"

  - wait

  - command: "docker pull us.gcr.io/bloom-sandbox/base/alpine"
    label: ":docker: Pull Bases"
    branches: "master"

  - command: "make build samples CI=yes"
    label: ":gcloud: Release: Images"
    branches: "master"

  - wait

  - command: "echo 'registry=https://npm.pkg.github.com/sgammon' > .npmrc && npm publish"
    label: ":octocat: + :npm: Staging: NPM"
    branches:
      - "master"
      - "release/*"
      - "feature/packaging"

  - command: "./gradlew build publish -Pgithub=true"
    label: ":octocat: + :mvn: Staging: Maven"
    branches:
      - "master"
      - "release/*"
      - "feature/packaging"

  - command: "make release-images CI=yes REGISTRY=docker.pkg.github.com/sgammon"
    label: ":octocat: + :whale: Staging: Docker"
    branches:
      - "master"
      - "release/*"
      - "feature/packaging"

  - wait

  - command: "rm -f .npmrc && npm publish"
    label: ":npm: Release: NPM"
    branches: "master"

  - command: "./gradlew build publish"
    label: ":mvn: Release: Maven"
    branches: "master"

  - command: "make release-images CI=yes"
    label: ":docker: Release: Docker"
    branches: "master"
