name: CI

on:
  push: {}

env:
  BAZELISK_VERSION: v1.2.1
  BUILD_TARGETS: //java/... //js/... //proto/...
  JAVA_TEST_TARGETS: //javatests/...

jobs:
  build:
    name: "Build & Test (Bazel ${{ matrix.bazel }} on ${{ matrix.os[0] }})"

    strategy:
      matrix:
        os: [["Ubuntu", "ubuntu-latest", "linux-amd64"], ["macOS Catalina", "macos-latest", "darwin-amd64"]]
        bazel: ["1.0.0", "2.0.0"]

    runs-on: ${{ matrix.os[1] }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1

      - name: Mount Cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-${{ matrix.bazel }}-${{ matrix.os[2] }}

      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-${{ matrix.os[2] }}"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-${{ matrix.os[2] }} "${GITHUB_WORKSPACE}/bin/bazelisk"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazelisk"

      - name: Select Bazel v${{ matrix.bazel }}
        run: |
          echo "${{ matrix.bazel }}" > .bazelversion

      - name: Build & Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazelisk" build ${BUILD_TARGETS}

      - name: Testsuite (Java)
        run: |
          "${GITHUB_WORKSPACE}/bin/bazelisk" test ${JAVA_TEST_TARGETS}

  docs:
    name: "Documentation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
