name: CI

on: [push]

jobs:
  # Job: Build on Linux
  #

  build-linux:
    name: '🛠️  Build: Linux'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        version: 376.0.0
        project_id: dyme-co
        install_components: 'kubectl'
    - name: Install Bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          ~/.cache
          ~/.config
          ~/Library/Caches
          ./node_modules
          ./.yarn-cache
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('maven_install.json') }}
    - name: Build default targets
      run: bazel build //...
    - name: Run testsuite
      run: bazel coverage //...
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: bazel-out/_coverage/_coverage_report.dat
        fail_ci_if_error: false
    - uses: actions/upload-artifact@v3
      name: "Upload coverage"
      continue-on-error: true
      with:
        name: coverage-linux
        if-no-files-found: warn
        path: bazel-out/_coverage
    - uses: actions/upload-artifact@v3
      name: "Upload testlogs"
      continue-on-error: true
      with:
        name: testlogs
        if-no-files-found: warn
        path: bazel-testlogs/**/test.xml

  # Job: Build on macOS
  #

  build-macos:
    name: '🛠️  Build:  macOS'
    runs-on: macos-11

    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-darwin-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: 376.0.0
          project_id: dyme-co
          install_components: 'kubectl'
      - name: Setup Docker
        uses: elide-dev/actions-setup-docker@master
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            ~/.cache
            ~/.config
            ~/Library/Caches
            ./node_modules
            ./.yarn-cache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('maven_install.json') }}
      - name: Build default targets
        run: bazel build //...
      - name: Run testsuite
        run: bazel coverage //...
      - uses: actions/upload-artifact@v3
        name: "Upload coverage"
        continue-on-error: true
        with:
          name: coverage-macos
          files: bazel-out/_coverage/_coverage_report.dat
          if-no-files-found: warn
